title: The Art of Playful Escalation
description: A book on Love, Sex, And Relationships in the 21st Century

google_analytics: UA-132737575-4

# theme: jekyll-theme-cayman

github:
  repository_url: https://consentandplay.com/
  repository_name: Consent & Play
  owner_url: https://goinglovefirst.com/
  owner_name: Love First™

kramdown:
  # input: GFM
  auto_ids: true
