title: The Art of Playful Escalation
tagline: A book on Love, Sex, And Relationships in the 21st Century
description: An upcoming book exploring Love, Sex, And Relationships in the 21st Century. Written by Faruk Ateş.

url:   https://artofplayfulescalation.com/
logo:  /assets/img/consent-play-logo-512-on-white.jpg
image:
  path: /assets/img/taope-mock-kindle.png
  height: 807
  width: 1200

defaults:
  - scope:
      path: ""
    values:
      image: https://artofplayfulescalation.com/assets/img/taope-mock-kindle.png
      alt: The Art of Playful Escalation book mockups

twitter:
  username: KuraFire
  card: summary

google_analytics: UA-132737575-4

# theme: jekyll-theme-cayman

github:
  repository_url: https://consentandplay.com/
  repository_name: Consent & Play
  owner_url: https://goinglovefirst.com/
  owner_name: Love First™

kramdown:
  auto_ids: true
  # input: GFM
